In [116]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [117]:
breast = pd.read_csv("breast_data.csv")

In [118]:
breast.head(3)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38           122.8     1001.0   
1    842517         M        20.57         17.77           132.9     1326.0   
2  84300903         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33            184.6      2019.0            0.1622   
1  ...          23.41            158.8      1956.0            0.1238   
2  ...          25.53            152.5      1709.0            0.1444   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  

[3 rows x 33 columns]

In [162]:
sam= breast.sample(6).iloc[2].values

In [163]:
sam

array([8610404, 'M', 16.07, 19.65, 104.1, 817.7, 0.09168, 0.08424,
       0.09769, 0.06638, 0.1798, 0.05391, 0.7474, 1.016, 5.029, 79.25,
       0.01082, 0.02203, 0.035, 0.01809, 0.0155, 0.001948, 19.77, 24.56,
       128.8, 1223.0, 0.15, 0.2045, 0.2829, 0.152, 0.265, 0.06387, nan],
      dtype=object)

In [88]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [89]:
breast = pd.read_csv("breast_data.csv")

In [90]:
breast.head(3)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38           122.8     1001.0   
1    842517         M        20.57         17.77           132.9     1326.0   
2  84300903         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33            184.6      2019.0            0.1622   
1  ...          23.41            158.8      1956.0            0.1238   
2  ...          25.53            152.5      1709.0            0.1444   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  

[3 rows x 33 columns]

In [95]:
sam= breast.sample(6).iloc[4].values

In [97]:
sam

array([925311, 'B', 11.2, 29.37, 70.67, 386.0, 0.07449, 0.03558, 0.0, 0.0,
       0.106, 0.05502, 0.3141, 3.896, 2.041, 22.81, 0.007594, 0.008878,
       0.0, 0.0, 0.01989, 0.001773, 11.92, 38.3, 75.19, 439.6, 0.09267,
       0.05494, 0.0, 0.0, 0.1566, 0.05905, nan], dtype=object)

In [98]:
breast.shape

(569, 33)

In [99]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [100]:
breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [101]:
breast.duplicated().sum()

0

In [102]:
breast.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [103]:
breast.drop(columns=['Unnamed: 32','id'], inplace=True)

In [104]:
breast.shape

(569, 31)

# Encoding Target Col

In [105]:
breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [106]:
le = LabelEncoder()

In [107]:
breast['diagnosis'] = le.fit_transform(breast['diagnosis'])

In [108]:
breast['diagnosis'].unique()

array([1, 0])

In [109]:
breast['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [23]:
breast.head(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                   0.1189  

[1 rows x 31 columns]

# Splitting Data

In [24]:
x = breast.drop(columns='diagnosis')
y = breast['diagnosis']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [26]:
x_train.shape

(455, 30)

In [27]:
x_test.shape

(114, 30)

# Scalling

In [28]:
sc = StandardScaler()

In [29]:
x_train =sc.fit_transform(x_train)

In [30]:
x_test = sc.transform(x_test)

In [31]:
x_train[0]

array([-1.44075296, -0.43531947, -1.36208497, -1.1391179 ,  0.78057331,
        0.71892128,  2.82313451, -0.11914956,  1.09266219,  2.45817261,
       -0.26380039, -0.01605246, -0.47041357, -0.47476088,  0.83836493,
        3.25102691,  8.43893667,  3.39198733,  2.62116574,  2.06120787,
       -1.23286131, -0.47630949, -1.24792009, -0.97396758,  0.72289445,
        1.18673232,  4.67282796,  0.9320124 ,  2.09724217,  1.88645014])

# Model Building

In [32]:
lr = LogisticRegression()

In [33]:
lr.fit(x_train, y_train)

LogisticRegression()

In [34]:
y_pred = lr.predict(x_test)

In [35]:
accuracy_score(y_test, y_pred)

0.9736842105263158

In [110]:
from sklearn.metrics import classification_report, confusion_matrix

# Model evaluation
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Confusion Matrix:
 [[70  1]
 [ 2 41]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



# Prediction System

In [37]:
input_text = (2.13018192e-01, -5.90201273e-01,  2.78151024e-01,
        7.93179680e-02,  1.47083851e+00,  1.16919292e+00,  1.00908719e+00,
        1.07711474e+00,  1.26019637e+00,  6.83612567e-01,  8.69160837e-02,
       -4.68975381e-01,  6.31952291e-02,  2.34972050e-02, -1.33445566e-03,
       -2.93138093e-04, -8.45111045e-02,  1.29797207e-01, -5.57825655e-01,
        2.28242912e-02,  5.35769651e-01,  3.02768997e-01,  5.99822963e-01,
        3.84469578e-01,  2.44036784e+00,  1.26100069e+00,  9.36116234e-01,
        1.35650577e+00,  1.07793067e+00,  1.26945274e+00)
np_df = np.asarray(input_text)
prediction = lr.predict(np_df.reshape(1,-1))

if prediction[0] == 1:
    print("Cancrous")
    
else:
    print("Non Cancrous")

Cancrous


In [38]:
x_train[10]

array([-0.4976419 ,  0.61365274, -0.49813131, -0.53102815, -0.57694824,
       -0.17494424, -0.36215622, -0.284859  ,  0.43345165,  0.17818232,
       -0.36844966,  0.55310406, -0.31671104, -0.40524636,  0.04025752,
       -0.03795529, -0.18043065,  0.16478901, -0.12170969,  0.23079329,
       -0.50044002,  0.81940367, -0.46922838, -0.53308833, -0.04910117,
       -0.04160193, -0.14913653,  0.09681787,  0.10617647,  0.49035329])

In [55]:
x_train[13]

array([-1.26011506, -0.16310297, -1.25095229, -1.0302484 , -0.45183767,
       -0.78300175, -0.7485231 , -0.87168083,  1.55520219,  0.19067922,
       -0.08632089,  0.27222162, -0.13980812, -0.36752201,  0.16765341,
       -0.30912281, -0.17700495, -0.31984743, -0.1192596 ,  0.0332407 ,
       -1.0601597 ,  0.01391574, -1.08654253, -0.8672748 , -0.35269495,
       -0.63639469, -0.70228078, -0.74450654,  0.42639563,  0.07696503])

In [40]:
# Dummy Data

In [41]:
import numpy as np
a =np.array([18.02,	15.10,	115.0,	1022.0,	0.1223,	0.2546,	0.2900,	0.1382,	0.2190,	0.0566,	1.095,	0.940,	8.000,	100.0,	0.0065,	0.0312,	0.0364,	0.0121,	0.0213,	0.0039,	24.10,	19.20,	160.0,	1783.0,	0.1740,	0.3774,	0.4390,	0.2102,	0.3190,	0.0865])
type(a) 
# Cancrous

numpy.ndarray

In [42]:
M	18.02	15.10	115.0	1022.0	0.1223	0.2546	0.2900	0.1382	0.2190	0.0566	1.095	0.940	8.000	100.0	0.0065	0.0312	0.0364	0.0121	0.0213	0.0039	24.10	19.20	160.0	1783.0	0.1740	0.3774	0.4390	0.2102	0.3190	0.0865
B	13.05	14.65	82.6	530.0	0.0910	0.0852	0.0710	0.0375	0.1780	0.0524	0.578	0.735	4.520	56.2	0.0049	0.0194	0.0241	0.0087	0.0201	0.0021	16.10	17.30	104.5	900.5	0.1456	0.1975	0.1850	0.0827	0.2156	0.0623
M	19.30	20.00	130.0	1327.5	0.1201	0.2526	0.2750	0.1300	0.2000	0.0598	1.020	0.900	8.200	120.0	0.0060	0.0289	0.0382	0.0152	0.0250	0.0040	25.00	18.90	155.0	2000.0	0.1830	0.3665	0.4150	0.2103	0.3322	0.0870
B	12.30	12.75	78.3	450.0	0.0894	0.0725	0.0654	0.0330	0.1500	0.0467	0.510	0.670	4.000	40.0	0.0038	0.0155	0.0201	0.0078	0.0152	0.0020	15.30	15.50	98.5	765.3	0.1302	0.1801	0.1608	0.0800	0.1952	0.0590
M	22.50	21.10	143.7	1820.0	0.1405	0.3154	0.3700	0.1687	0.2302	0.0667	1.200	1.050	9.500	175.0	0.0081	0.0321	0.0407	0.0135	0.0272	0.0043	28.00	21.50	180.0	2500.0	0.1990	0.4321	0.5200	0.2708	0.4005	0.0980


SyntaxError: invalid syntax (2238052698.py, line 1)

In [43]:
import numpy as np

# Provided data
data = [
    ['M', 18.02, 15.10, 115.0, 1022.0, 0.1223, 0.2546, 0.2900, 0.1382, 0.2190, 0.0566, 1.095, 0.940, 8.000, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.10, 19.20, 160.0, 1783.0, 0.1740, 0.3774, 0.4390, 0.2102, 0.3190, 0.0865],
    ['B', 13.05, 14.65, 82.6, 530.0, 0.0910, 0.0852, 0.0710, 0.0375, 0.1780, 0.0524, 0.578, 0.735, 4.520, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.10, 17.30, 104.5, 900.5, 0.1456, 0.1975, 0.1850, 0.0827, 0.2156, 0.0623],
    ['M', 19.30, 20.00, 130.0, 1327.5, 0.1201, 0.2526, 0.2750, 0.1300, 0.2000, 0.0598, 1.020, 0.900, 8.200, 120.0, 0.0060, 0.0289, 0.0382, 0.0152, 0.0250, 0.0040, 25.00, 18.90, 155.0, 2000.0, 0.1830, 0.3665, 0.4150, 0.2103, 0.3322, 0.0870],
    ['B', 12.30, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.0330, 0.1500, 0.0467, 0.510, 0.670, 4.000, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.0020, 15.30, 15.50, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.0800, 0.1952, 0.0590],
    ['M', 22.50, 21.10, 143.7, 1820.0, 0.1405, 0.3154, 0.3700, 0.1687, 0.2302, 0.0667, 1.200, 1.050, 9.500, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.0043, 28.00, 21.50, 180.0, 2500.0, 0.1990, 0.4321, 0.5200, 0.2708, 0.4005, 0.0980]
]

# Remove the second column (label) and convert remaining data to numpy arrays
arrays = [np.array(row[2:], dtype=float) for row in data]

for array in arrays:
    print(array)
    print(type(array))


[1.510e+01 1.150e+02 1.022e+03 1.223e-01 2.546e-01 2.900e-01 1.382e-01
 2.190e-01 5.660e-02 1.095e+00 9.400e-01 8.000e+00 1.000e+02 6.500e-03
 3.120e-02 3.640e-02 1.210e-02 2.130e-02 3.900e-03 2.410e+01 1.920e+01
 1.600e+02 1.783e+03 1.740e-01 3.774e-01 4.390e-01 2.102e-01 3.190e-01
 8.650e-02]
<class 'numpy.ndarray'>
[1.465e+01 8.260e+01 5.300e+02 9.100e-02 8.520e-02 7.100e-02 3.750e-02
 1.780e-01 5.240e-02 5.780e-01 7.350e-01 4.520e+00 5.620e+01 4.900e-03
 1.940e-02 2.410e-02 8.700e-03 2.010e-02 2.100e-03 1.610e+01 1.730e+01
 1.045e+02 9.005e+02 1.456e-01 1.975e-01 1.850e-01 8.270e-02 2.156e-01
 6.230e-02]
<class 'numpy.ndarray'>
[2.0000e+01 1.3000e+02 1.3275e+03 1.2010e-01 2.5260e-01 2.7500e-01
 1.3000e-01 2.0000e-01 5.9800e-02 1.0200e+00 9.0000e-01 8.2000e+00
 1.2000e+02 6.0000e-03 2.8900e-02 3.8200e-02 1.5200e-02 2.5000e-02
 4.0000e-03 2.5000e+01 1.8900e+01 1.5500e+02 2.0000e+03 1.8300e-01
 3.6650e-01 4.1500e-01 2.1030e-01 3.3220e-01 8.7000e-02]
<class 'numpy.ndarray'>
[1.275e+01 

In [54]:
import numpy as np

# Provided data
data = [
    ['M', 18.02, 15.10, 115.0, 1022.0, 0.1223, 0.2546, 0.2900, 0.1382, 0.2190, 0.0566, 1.095, 0.940, 8.000, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.10, 19.20, 160.0, 1783.0, 0.1740, 0.3774, 0.4390, 0.2102, 0.3190, 0.0865],
    ['B', 13.05, 14.65, 82.6, 530.0, 0.0910, 0.0852, 0.0710, 0.0375, 0.1780, 0.0524, 0.578, 0.735, 4.520, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.10, 17.30, 104.5, 900.5, 0.1456, 0.1975, 0.1850, 0.0827, 0.2156, 0.0623],
    ['M', 19.30, 20.00, 130.0, 1327.5, 0.1201, 0.2526, 0.2750, 0.1300, 0.2000, 0.0598, 1.020, 0.900, 8.200, 120.0, 0.0060, 0.0289, 0.0382, 0.0152, 0.0250, 0.0040, 25.00, 18.90, 155.0, 2000.0, 0.1830, 0.3665, 0.4150, 0.2103, 0.3322, 0.0870],
    ['B', 12.30, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.0330, 0.1500, 0.0467, 0.510, 0.670, 4.000, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.0020, 15.30, 15.50, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.0800, 0.1952, 0.0590],
    ['M', 22.50, 21.10, 143.7, 1820.0, 0.1405, 0.3154, 0.3700, 0.1687, 0.2302, 0.0667, 1.200, 1.050, 9.500, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.0043, 28.00, 21.50, 180.0, 2500.0, 0.1990, 0.4321, 0.5200, 0.2708, 0.4005, 0.0980],
    ['B', 12.06,	18.90,	76.66,	445.3,	0.08386,	0.05794,	0.00751,	0.008488,	0.1555,	...	13.64,	27.06,	86.54,	562.6,	0.1289,	0.1352,	0.04506,	0.05093,	0.2880,	0.08083]
]

# Remove the second column (label) and convert remaining data to numpy arrays
arrays = [np.array(row[1:], dtype=float) for row in data]

# Print arrays with each value followed by a comma
for array in arrays:
    print("("+', '.join(f"{x}" for x in array) + ")")


(18.02, 15.1, 115.0, 1022.0, 0.1223, 0.2546, 0.29, 0.1382, 0.219, 0.0566, 1.095, 0.94, 8.0, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.1, 19.2, 160.0, 1783.0, 0.174, 0.3774, 0.439, 0.2102, 0.319, 0.0865)
(13.05, 14.65, 82.6, 530.0, 0.091, 0.0852, 0.071, 0.0375, 0.178, 0.0524, 0.578, 0.735, 4.52, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.1, 17.3, 104.5, 900.5, 0.1456, 0.1975, 0.185, 0.0827, 0.2156, 0.0623)
(19.3, 20.0, 130.0, 1327.5, 0.1201, 0.2526, 0.275, 0.13, 0.2, 0.0598, 1.02, 0.9, 8.2, 120.0, 0.006, 0.0289, 0.0382, 0.0152, 0.025, 0.004, 25.0, 18.9, 155.0, 2000.0, 0.183, 0.3665, 0.415, 0.2103, 0.3322, 0.087)
(12.3, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.033, 0.15, 0.0467, 0.51, 0.67, 4.0, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.002, 15.3, 15.5, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.08, 0.1952, 0.059)
(22.5, 21.1, 143.7, 1820.0, 0.1405, 0.3154, 0.37, 0.1687, 0.2302, 0.0667, 1.2, 1.05, 9.5, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.

# Export

In [44]:
import pickle
pickle.dump(lr, open('breast_cancer_model.pkl', 'wb'))

In [98]:
breast.shape

(569, 33)

In [99]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [100]:
breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [101]:
breast.duplicated().sum()

0

In [102]:
breast.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [103]:
breast.drop(columns=['Unnamed: 32','id'], inplace=True)

In [104]:
breast.shape

(569, 31)

# Encoding Target Col

In [105]:
breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [106]:
le = LabelEncoder()

In [107]:
breast['diagnosis'] = le.fit_transform(breast['diagnosis'])

In [108]:
breast['diagnosis'].unique()

array([1, 0])

In [109]:
breast['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [23]:
breast.head(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                   0.1189  

[1 rows x 31 columns]

# Splitting Data

In [24]:
x = breast.drop(columns='diagnosis')
y = breast['diagnosis']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [26]:
x_train.shape

(455, 30)

In [27]:
x_test.shape

(114, 30)

# Scalling

In [28]:
sc = StandardScaler()

In [29]:
x_train =sc.fit_transform(x_train)

In [30]:
x_test = sc.transform(x_test)

In [31]:
x_train[0]

array([-1.44075296, -0.43531947, -1.36208497, -1.1391179 ,  0.78057331,
        0.71892128,  2.82313451, -0.11914956,  1.09266219,  2.45817261,
       -0.26380039, -0.01605246, -0.47041357, -0.47476088,  0.83836493,
        3.25102691,  8.43893667,  3.39198733,  2.62116574,  2.06120787,
       -1.23286131, -0.47630949, -1.24792009, -0.97396758,  0.72289445,
        1.18673232,  4.67282796,  0.9320124 ,  2.09724217,  1.88645014])

# Model Building

In [32]:
lr = LogisticRegression()

In [33]:
lr.fit(x_train, y_train)

LogisticRegression()

In [34]:
y_pred = lr.predict(x_test)

In [35]:
accuracy_score(y_test, y_pred)

0.9736842105263158

In [110]:
from sklearn.metrics import classification_report, confusion_matrix

# Model evaluation
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Confusion Matrix:
 [[70  1]
 [ 2 41]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



# Prediction System

In [37]:
input_text = (2.13018192e-01, -5.90201273e-01,  2.78151024e-01,
        7.93179680e-02,  1.47083851e+00,  1.16919292e+00,  1.00908719e+00,
        1.07711474e+00,  1.26019637e+00,  6.83612567e-01,  8.69160837e-02,
       -4.68975381e-01,  6.31952291e-02,  2.34972050e-02, -1.33445566e-03,
       -2.93138093e-04, -8.45111045e-02,  1.29797207e-01, -5.57825655e-01,
        2.28242912e-02,  5.35769651e-01,  3.02768997e-01,  5.99822963e-01,
        3.84469578e-01,  2.44036784e+00,  1.26100069e+00,  9.36116234e-01,
        1.35650577e+00,  1.07793067e+00,  1.26945274e+00)
np_df = np.asarray(input_text)
prediction = lr.predict(np_df.reshape(1,-1))

if prediction[0] == 1:
    print("Cancerous")
    
else:
    print("Non Cancerous")

Cancrous


In [38]:
x_train[10]

array([-0.4976419 ,  0.61365274, -0.49813131, -0.53102815, -0.57694824,
       -0.17494424, -0.36215622, -0.284859  ,  0.43345165,  0.17818232,
       -0.36844966,  0.55310406, -0.31671104, -0.40524636,  0.04025752,
       -0.03795529, -0.18043065,  0.16478901, -0.12170969,  0.23079329,
       -0.50044002,  0.81940367, -0.46922838, -0.53308833, -0.04910117,
       -0.04160193, -0.14913653,  0.09681787,  0.10617647,  0.49035329])

In [55]:
x_train[13]

array([-1.26011506, -0.16310297, -1.25095229, -1.0302484 , -0.45183767,
       -0.78300175, -0.7485231 , -0.87168083,  1.55520219,  0.19067922,
       -0.08632089,  0.27222162, -0.13980812, -0.36752201,  0.16765341,
       -0.30912281, -0.17700495, -0.31984743, -0.1192596 ,  0.0332407 ,
       -1.0601597 ,  0.01391574, -1.08654253, -0.8672748 , -0.35269495,
       -0.63639469, -0.70228078, -0.74450654,  0.42639563,  0.07696503])

In [40]:
# Dummy Data

In [41]:
import numpy as np
a =np.array([18.02,	15.10,	115.0,	1022.0,	0.1223,	0.2546,	0.2900,	0.1382,	0.2190,	0.0566,	1.095,	0.940,	8.000,	100.0,	0.0065,	0.0312,	0.0364,	0.0121,	0.0213,	0.0039,	24.10,	19.20,	160.0,	1783.0,	0.1740,	0.3774,	0.4390,	0.2102,	0.3190,	0.0865])
type(a) 
# Cancrous

numpy.ndarray

In [42]:
M	18.02	15.10	115.0	1022.0	0.1223	0.2546	0.2900	0.1382	0.2190	0.0566	1.095	0.940	8.000	100.0	0.0065	0.0312	0.0364	0.0121	0.0213	0.0039	24.10	19.20	160.0	1783.0	0.1740	0.3774	0.4390	0.2102	0.3190	0.0865
B	13.05	14.65	82.6	530.0	0.0910	0.0852	0.0710	0.0375	0.1780	0.0524	0.578	0.735	4.520	56.2	0.0049	0.0194	0.0241	0.0087	0.0201	0.0021	16.10	17.30	104.5	900.5	0.1456	0.1975	0.1850	0.0827	0.2156	0.0623
M	19.30	20.00	130.0	1327.5	0.1201	0.2526	0.2750	0.1300	0.2000	0.0598	1.020	0.900	8.200	120.0	0.0060	0.0289	0.0382	0.0152	0.0250	0.0040	25.00	18.90	155.0	2000.0	0.1830	0.3665	0.4150	0.2103	0.3322	0.0870
B	12.30	12.75	78.3	450.0	0.0894	0.0725	0.0654	0.0330	0.1500	0.0467	0.510	0.670	4.000	40.0	0.0038	0.0155	0.0201	0.0078	0.0152	0.0020	15.30	15.50	98.5	765.3	0.1302	0.1801	0.1608	0.0800	0.1952	0.0590
M	22.50	21.10	143.7	1820.0	0.1405	0.3154	0.3700	0.1687	0.2302	0.0667	1.200	1.050	9.500	175.0	0.0081	0.0321	0.0407	0.0135	0.0272	0.0043	28.00	21.50	180.0	2500.0	0.1990	0.4321	0.5200	0.2708	0.4005	0.0980


SyntaxError: invalid syntax (2238052698.py, line 1)

In [43]:
import numpy as np

# Provided data
data = [
    ['M', 18.02, 15.10, 115.0, 1022.0, 0.1223, 0.2546, 0.2900, 0.1382, 0.2190, 0.0566, 1.095, 0.940, 8.000, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.10, 19.20, 160.0, 1783.0, 0.1740, 0.3774, 0.4390, 0.2102, 0.3190, 0.0865],
    ['B', 13.05, 14.65, 82.6, 530.0, 0.0910, 0.0852, 0.0710, 0.0375, 0.1780, 0.0524, 0.578, 0.735, 4.520, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.10, 17.30, 104.5, 900.5, 0.1456, 0.1975, 0.1850, 0.0827, 0.2156, 0.0623],
    ['M', 19.30, 20.00, 130.0, 1327.5, 0.1201, 0.2526, 0.2750, 0.1300, 0.2000, 0.0598, 1.020, 0.900, 8.200, 120.0, 0.0060, 0.0289, 0.0382, 0.0152, 0.0250, 0.0040, 25.00, 18.90, 155.0, 2000.0, 0.1830, 0.3665, 0.4150, 0.2103, 0.3322, 0.0870],
    ['B', 12.30, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.0330, 0.1500, 0.0467, 0.510, 0.670, 4.000, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.0020, 15.30, 15.50, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.0800, 0.1952, 0.0590],
    ['M', 22.50, 21.10, 143.7, 1820.0, 0.1405, 0.3154, 0.3700, 0.1687, 0.2302, 0.0667, 1.200, 1.050, 9.500, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.0043, 28.00, 21.50, 180.0, 2500.0, 0.1990, 0.4321, 0.5200, 0.2708, 0.4005, 0.0980]
]

# Remove the second column (label) and convert remaining data to numpy arrays
arrays = [np.array(row[2:], dtype=float) for row in data]

for array in arrays:
    print(array)
    print(type(array))


[1.510e+01 1.150e+02 1.022e+03 1.223e-01 2.546e-01 2.900e-01 1.382e-01
 2.190e-01 5.660e-02 1.095e+00 9.400e-01 8.000e+00 1.000e+02 6.500e-03
 3.120e-02 3.640e-02 1.210e-02 2.130e-02 3.900e-03 2.410e+01 1.920e+01
 1.600e+02 1.783e+03 1.740e-01 3.774e-01 4.390e-01 2.102e-01 3.190e-01
 8.650e-02]
<class 'numpy.ndarray'>
[1.465e+01 8.260e+01 5.300e+02 9.100e-02 8.520e-02 7.100e-02 3.750e-02
 1.780e-01 5.240e-02 5.780e-01 7.350e-01 4.520e+00 5.620e+01 4.900e-03
 1.940e-02 2.410e-02 8.700e-03 2.010e-02 2.100e-03 1.610e+01 1.730e+01
 1.045e+02 9.005e+02 1.456e-01 1.975e-01 1.850e-01 8.270e-02 2.156e-01
 6.230e-02]
<class 'numpy.ndarray'>
[2.0000e+01 1.3000e+02 1.3275e+03 1.2010e-01 2.5260e-01 2.7500e-01
 1.3000e-01 2.0000e-01 5.9800e-02 1.0200e+00 9.0000e-01 8.2000e+00
 1.2000e+02 6.0000e-03 2.8900e-02 3.8200e-02 1.5200e-02 2.5000e-02
 4.0000e-03 2.5000e+01 1.8900e+01 1.5500e+02 2.0000e+03 1.8300e-01
 3.6650e-01 4.1500e-01 2.1030e-01 3.3220e-01 8.7000e-02]
<class 'numpy.ndarray'>
[1.275e+01 

In [54]:
import numpy as np

# Provided data
data = [
    ['M', 18.02, 15.10, 115.0, 1022.0, 0.1223, 0.2546, 0.2900, 0.1382, 0.2190, 0.0566, 1.095, 0.940, 8.000, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.10, 19.20, 160.0, 1783.0, 0.1740, 0.3774, 0.4390, 0.2102, 0.3190, 0.0865],
    ['B', 13.05, 14.65, 82.6, 530.0, 0.0910, 0.0852, 0.0710, 0.0375, 0.1780, 0.0524, 0.578, 0.735, 4.520, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.10, 17.30, 104.5, 900.5, 0.1456, 0.1975, 0.1850, 0.0827, 0.2156, 0.0623],
    ['M', 19.30, 20.00, 130.0, 1327.5, 0.1201, 0.2526, 0.2750, 0.1300, 0.2000, 0.0598, 1.020, 0.900, 8.200, 120.0, 0.0060, 0.0289, 0.0382, 0.0152, 0.0250, 0.0040, 25.00, 18.90, 155.0, 2000.0, 0.1830, 0.3665, 0.4150, 0.2103, 0.3322, 0.0870],
    ['B', 12.30, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.0330, 0.1500, 0.0467, 0.510, 0.670, 4.000, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.0020, 15.30, 15.50, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.0800, 0.1952, 0.0590],
    ['M', 22.50, 21.10, 143.7, 1820.0, 0.1405, 0.3154, 0.3700, 0.1687, 0.2302, 0.0667, 1.200, 1.050, 9.500, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.0043, 28.00, 21.50, 180.0, 2500.0, 0.1990, 0.4321, 0.5200, 0.2708, 0.4005, 0.0980],
    ['B', 12.06,	18.90,	76.66,	445.3,	0.08386,	0.05794,	0.00751,	0.008488,	0.1555,	...	13.64,	27.06,	86.54,	562.6,	0.1289,	0.1352,	0.04506,	0.05093,	0.2880,	0.08083]
]

# Remove the second column (label) and convert remaining data to numpy arrays
arrays = [np.array(row[1:], dtype=float) for row in data]

# Print arrays with each value followed by a comma
for array in arrays:
    print("("+', '.join(f"{x}" for x in array) + ")")


(18.02, 15.1, 115.0, 1022.0, 0.1223, 0.2546, 0.29, 0.1382, 0.219, 0.0566, 1.095, 0.94, 8.0, 100.0, 0.0065, 0.0312, 0.0364, 0.0121, 0.0213, 0.0039, 24.1, 19.2, 160.0, 1783.0, 0.174, 0.3774, 0.439, 0.2102, 0.319, 0.0865)
(13.05, 14.65, 82.6, 530.0, 0.091, 0.0852, 0.071, 0.0375, 0.178, 0.0524, 0.578, 0.735, 4.52, 56.2, 0.0049, 0.0194, 0.0241, 0.0087, 0.0201, 0.0021, 16.1, 17.3, 104.5, 900.5, 0.1456, 0.1975, 0.185, 0.0827, 0.2156, 0.0623)
(19.3, 20.0, 130.0, 1327.5, 0.1201, 0.2526, 0.275, 0.13, 0.2, 0.0598, 1.02, 0.9, 8.2, 120.0, 0.006, 0.0289, 0.0382, 0.0152, 0.025, 0.004, 25.0, 18.9, 155.0, 2000.0, 0.183, 0.3665, 0.415, 0.2103, 0.3322, 0.087)
(12.3, 12.75, 78.3, 450.0, 0.0894, 0.0725, 0.0654, 0.033, 0.15, 0.0467, 0.51, 0.67, 4.0, 40.0, 0.0038, 0.0155, 0.0201, 0.0078, 0.0152, 0.002, 15.3, 15.5, 98.5, 765.3, 0.1302, 0.1801, 0.1608, 0.08, 0.1952, 0.059)
(22.5, 21.1, 143.7, 1820.0, 0.1405, 0.3154, 0.37, 0.1687, 0.2302, 0.0667, 1.2, 1.05, 9.5, 175.0, 0.0081, 0.0321, 0.0407, 0.0135, 0.0272, 0.

# Export

In [44]:
import pickle
pickle.dump(lr, open('breast_cancer_model.pkl', 'wb'))

In [111]:
# Pipeline Code

from sklearn.pipeline import Pipeline

# Load the dataset
breast = pd.read_csv("breast_data.csv")

# Drop unnecessary columns
breast.drop(columns=['Unnamed: 32', 'id'], inplace=True)

# Remove null
breast.dropna(inplace=True)

#  Remove Duplicated
breast.drop_duplicates()

# Encode the target column
le = LabelEncoder()
breast['diagnosis'] = le.fit_transform(breast['diagnosis'])

# Split the data into features and target
X = breast.drop(columns='diagnosis')
y = breast['diagnosis']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a pipeline with scaling and logistic regression
pipeline = Pipeline([
    ('scaler', StandardScaler()),               # Step 1: Standardize the data
    ('logistic_regression', LogisticRegression())  # Step 2: Logistic Regression model
])

# Fit the model
pipeline.fit(X_train, y_train)

# Make predictions
y_pred = pipeline.predict(X_test)



In [112]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print results
print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)



Accuracy: 0.9737
Confusion Matrix:
 [[70  1]
 [ 2 41]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [151]:
# Prediction System
input_data = (2.13018192e-01, -5.90201273e-01,  2.78151024e-01,
              7.93179680e-02,  1.47083851e+00,  1.16919292e+00,  1.00908719e+00,
              1.07711474e+00,  1.26019637e+00,  6.83612567e-01,  8.69160837e-02,
              -4.68975381e-01,  6.31952291e-02,  2.34972050e-02, -1.33445566e-03,
              -2.93138093e-04, -8.45111045e-02,  1.29797207e-01, -5.57825655e-01,
              2.28242912e-02,  5.35769651e-01,  3.02768997e-01,  5.99822963e-01,
              3.84469578e-01,  2.44036784e+00,  1.26100069e+00,  9.36116234e-01,
              1.35650577e+00,  1.07793067e+00,  1.26945274e+00)

# Make a prediction with the trained pipeline
prediction = pipeline.predict(np.array(input_data).reshape(1, -1))

if prediction[0] == 1:
    print("Cancerous")
else:
    print("Non Cancerous")


Cancerous


C:\Users\PC\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [114]:
import pickle

# Save the pipeline to a file
with open('breast_cancer_pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)
